---
- name: wait for jenkins to restart
  local_action:
    module: uri
    url: "{{ JENKINS_URL }}/login"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 20
